### ISSUE TITLE
Дублируется адрес сайта в шапке скрипта

### ISSUE THREAD

**Issue by Realex-fire** [imShara/jslock-roi#1]
Пример:
Допустим что адрес сайта на который установлен скрипт "http://111-111.p.ht", при нажатии на имя сайта в шапке скрипта, скрипт должен ссылать пользователя на сайт "http://111-111.p.ht", но вместо этого скрипт ссылает пользователя на дублированый адрес сайта "http://111-111.p.ht/111-111.p.ht"

**Comment by imShara** [comment]
Исправлено, спасибо
