### ISSUE TITLE
Белый экран.

### ISSUE THREAD

**Issue by Realex-fire** [imShara/jslock-roi#13]
Скрипт на lockjs.googlecode.com/git/lock.min.js, упал полностью, показывает белый экран.

**Comment by imShara** [comment]
Перенесено на //cdn.jsdelivr.net/jslock/lock.min.js больше падений быть не должно.
Гуглокод, увы, решил не брать на себя такую нагрузку. Поспешно выбрали Google после того, как rawGithHub "попросил"
